version: '3.8'

name: kingpong

services:
    backend:
      container_name: backend
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - 3030:3030
      restart: always
      depends_on:
        - db
        - minio
        - prisma
      env_file:
        - './.env'

    frontend:
      container_name: frontend
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - 5050:5050
      restart: always
      env_file:
        - './.env'

    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - 8080:80
        depends_on:
          - backend
          - frontend
        restart: always
        volumes:
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
        extra_hosts:
            - 'host.docker.internal:host-gateway'

    db:
        container_name: db
        image: postgres
        restart: always
        env_file:
            - './.env'
        ports:
            - 5432:5432
        volumes:
            - dbdata:/var/lib/postgresql/data

    minio:
        container_name: minio
        image: bitnami/minio
        restart: always
        env_file:
            - './.env'
        ports:
            - 9000:9000
            - 9001:9001
        volumes:
            - minio-data:/bitnami/minio/data

    prisma:
        container_name: prisma-config
        image: node:20.6.1
        volumes:
            - ./backend:/app
            - ./config/prisma/prisma.sh:/app/prisma.sh
        working_dir: /app
        env_file:
            - './.env'
        command: sh prisma.sh
        depends_on:
            - db

volumes:
    dbdata:
    minio-data:
